### ISSUE TITLE
Transaction Isolations Levels

### ISSUE THREAD

**Issue by iamananya** [iamananya/Ginco-mission-2#7]
In the provided code, **MySQL** is used as the database for managing seat bookings. The transaction isolation levels determine how concurrent transactions interact with each other and affect data consistency.

- **Read Uncommitted**:

This isolation level allows transactions to read uncommitted data from other transactions, potentially leading to dirty reads, non-repeatable reads, and phantom reads.

- **Read Committed**:

This isolation level ensures that a transaction only reads committed data from other transactions, preventing dirty reads.

- **Repeatable Read**:

This isolation level ensures that a transaction sees a consistent snapshot of the data throughout its duration, preventing dirty reads and non-repeatable reads.
The provided code uses the default isolation level of MySQL, which is usually Repeatable Read.
The code starts a new transaction using tx := db.Begin(), performs queries and updates within the transaction, and commits the transaction using tx.Commit().
The use of transactions in the code ensures consistency by providing a stable snapshot of the data during the transaction's execution.

- **Serializable**:

This isolation level provides the highest level of isolation, guaranteeing strict consistency by preventing dirty reads, non-repeatable reads, and phantom reads. It achieves this by using locks that restrict concurrent access to data.

Using a **higher isolation** level like Serializable can ensure **stricter consistency** and prevent conflicts between concurrent transactions.
Higher isolation levels may come with a trade-off in terms of **increased lock contention** and **potential performance impact**. It's important to determine the optimal balance between consistency and performance for your specific use case.

I used the function to test the concurrency and performance. Concurrency was implemented using goroutines.

```
func BenchmarkSeatBooking(b *testing.B) {
	router := gin.Default()
	router.POST("/book-seat", func(c *gin.Context) {
		var seat models.Seat
		if err := c.ShouldBindJSON(&seat); err != nil {
			c.JSON(http.StatusBadRequest, gin.H{"error": err.Error()})
			return
		}

		db := config.GetDB()
		tx := db.Begin()
		tx.Exec("SET TRANSACTION ISOLATION LEVEL SERIALIZABLE")

		existingSeat := models.GetSeatByNumberAndShowID(tx, seat.SeatNumber, seat.ShowID)
		if existingSeat != nil && existingSeat.IsBooked {
			tx.Rollback()
			fmt.Println("Seat is already booked")
			c.JSON(http.StatusConflict, gin.H{"error": "Seat is already booked"})
			return
		}

		seat.IsBooked = true
		if err := models.CreateSeat(tx, &seat); err != nil {
			tx.Rollback()
			fmt.Println("Failed to create seat")
			c.JSON(http.StatusInternalServerError, gin.H{"error": "Failed to create seat"})
			return
		}

		tx.Commit()

		c.JSON(http.StatusCreated, seat)
	})

	// Create a new HTTP request for seat booking
	payload := []byte(`{"show_id": 1,
        "seat_number": "C-3",
        "seat_type_id": 1,
        "is_booked": true,
        "user_id":6}`)
	fmt.Println("Payload:", string(payload))
	req, _ := http.NewRequest(http.MethodPost, "/book-seat", bytes.NewBuffer(payload))
	req.Header.Set("Content-Type", "application/json")

	b.ResetTimer()
	b.RunParallel(func(pb *testing.PB) {
		for pb.Next() {
			w := httptest.NewRecorder()
			router.ServeHTTP(w, req)
		}
	})
}
```

THe following output was obtained
```
2023/07/03 11:45:20    92822         12835 ns/op ->Repeatable read
2023/07/03 11:46:21    92928         12847 ns/op ->Read Committed
2023/07/03 11:47:12    91572         12815 ns/op ->Searializable
```
Since the performance is similar with read committed and serializable. It's better to use the default isolation of MySQL and not explicitly add any other isolation level. 

1. Repeatable Read allows concurrent transactions to read and modify data without blocking each other to prevent conflicting updates. On the other hand, Serializable imposes strict locks on the entire data set, potentially causing higher contention and reduced concurrency. In a movie ticket booking scenario with a large number of concurrent users, Serializable isolation may lead to decreased performance and scalability.
2. Both Repeatable Read and Serializable isolation levels provide a high degree of data consistency by preventing dirty reads, non-repeatable reads, and phantom reads.
3. Repeatable Read ensures consistent data throughout a transaction. If a seat is selected by one user, others trying to select the same seat are blocked until the first transaction completes. This avoids conflicts and simplifies handling in the application.

Considering these factors, Repeatable Read is a suitable choice for concurrent seat bookings in a movie ticket booking application. It provides a good balance between data consistency, concurrency, and performance.

**Comment by iamananya** [comment]
@GuiltyMorishita I have explained the transaction isolation levels in this issue. Please review this and suggest changes.

**Comment by GuiltyMorishita** [comment]
@iamananya I guess it's good.

Let's see now, Please explain here the results of actually causing dirty leads, non-repeatable leads, and phantom leads, including commands.

**Comment by iamananya** [comment]
Thank you @GuiltyMorishita for the review. I will update the above results as well.

**Comment by GuiltyMorishita** [comment]
@iamananya Next Task
> Let's see now, Please explain here the results of actually causing dirty leads, non-repeatable leads, and phantom leads, including commands.

**Comment by iamananya** [comment]
Okay @GuiltyMorishita san.

**Comment by iamananya** [comment]
@GuiltyMorishita Please review this.

This is the image of the first transaction (**Console 1**)
![image](https://github.com/iamananya/Ginco-mission-2/assets/61614556/69e6edd5-84a1-4899-913a-2436ca53c863)
![image](https://github.com/iamananya/Ginco-mission-2/assets/61614556/41b1665a-b675-45b9-b0df-00da7466829a)



This is the image for the second transaction (**Console 2**)
![image](https://github.com/iamananya/Ginco-mission-2/assets/61614556/0263087f-e2a4-464a-9f99-7090780fb14d)

The actual database looks like:
![image](https://github.com/iamananya/Ginco-mission-2/assets/61614556/5a0aee81-7693-42cb-9402-dafc7b6883e9)
![image](https://github.com/iamananya/Ginco-mission-2/assets/61614556/4ecf13fd-0041-4fd1-8eff-e5ef6a7076e8)

My SQL by default follows repeatable-read type isolation which prevents dirty reads, non-repeatable reads, and phantom reads.
The flow of the transactions is as follows

Console 1:
* Start transaction
* Read table seats with `seat_number = 'A-1' AND show_id = 1`

Console 2:
* Update the seat to is_booked=true which was initially false.

Console 1:
* Read table seats again with `seat_number = 'A-1' AND show_id = 1`. No changes are reflected. Hence **Dirty Nead has been prevented** here.

Console 2: 
* Commit the changes.

Console 1:
* Read the table seats again with with `seat_number = 'A-1' AND show_id = 1`. No changes have been shown. Hence **Non-Repeatable Reads have been prevented**.

Console 1:
* Read all rows from table seats.

Console 2:
* Insert a new seat C-1 into the table seats.

Console 1:
* Read all rows from table seats. The new entry is not visible. This **prevents Phantom Reads.**

In MySQL with the "Repeatable Read" isolation level, the default behavior is to prevent phantom reads by using consistent snapshots. So, the second read in Console 1 will only show the data that existed at the start of the transaction, and the newly inserted seat record will not be visible.

MySQL's "Repeatable Read" isolation level achieves this by acquiring a shared lock on the entire range of rows being read. This ensures that no other transactions can insert new rows within that range, effectively preventing phantom reads.

Reference: https://stackoverflow.com/questions/4034976/difference-between-read-commited-and-repeatable-read-in-sql-server

**Comment by GuiltyMorishita** [comment]
LGTM!
